CREATE TABLE IF NOT EXISTS stocks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  price NUMERIC
);

CREATE TABLE IF NOT EXISTS bets (
    id SERIAL PRIMARY KEY,
    user_address VARCHAR(42),
    bet_id BIGINT,
    symbol VARCHAR(20),
    lower NUMERIC,
    upper NUMERIC,
    amount NUMERIC,
    deadline BIGINT,
    datenow BIGINT,
    ownerfee NUMERIC,
    winamount DOUBLE PRECISION DEFAULT 0,
    lossfee DOUBLE PRECISION DEFAULT 0
);

ALTER TABLE stocks ADD COLUMN IF NOT EXISTS week_52_range VARCHAR(100);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS volume BIGINT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS market_cap BIGINT;

ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory24h JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory5d JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory1m JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory6m JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory1y JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistory5y JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pricehistoryall JSONB;

ALTER TABLE stocks ADD COLUMN IF NOT EXISTS avgintervalum NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS avgtime NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS avgvolume NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS total_bet_amount NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS link VARCHAR(100);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS network TEXT DEFAULT 'Sepolia Testnet';